name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    # install boost C++
    - name: boost
      run: sudo apt update && sudo apt install -yq libboost-all-dev
    
    # compiling
    - name: make
      run: make
