name: C/C++ CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: compile and run
      run: g++ -std=gnu++17 -O2 -g -pipe -D DEBUG ./src/main.cpp
